apiVersion: apps/v1
kind: Deployment
metadata:
  name: lms
spec:
  replicas: 2
  selector:
    matchLabels:
      app: lms
  template:
    metadata:
      labels:
        app: lms
    spec:
      containers:
      - name: lms
        image: venureddy3417/lms-fe:IMAGE_VERSION
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: lms
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: lms